import { useState, useEffect, useRef } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { brandDNA } from '../config/brand-dna';
import AvailableDot from './AvailableDot';

const serviceItems = brandDNA.services.map((s) => ({ label: s.name, slug: s.slug }));

// Rule 68: pipeline default is HOMEPAGE-ONLY build for sales demos. Nav links
// scroll to homepage section anchors (#about, #services, etc.) so there are
// no broken /about, /services, /blog page routes in the dist. The hash anchors
// map to id="..." set on each homepage section component (Services,
// OurWork=#gallery, Blog, FAQ, WhyChooseUs=#why, OurProcess=#process,
// Reviews, SpecialOffers=#financing, Founder=#about, CTABanner=#cta-form,
// ServiceAreas=#service-area). When the sale closes, the manual full build
// restores per-page routes and these hrefs should flip back to absolute paths.
const navLinks = [
  { label: 'Home', to: '/' },
  { label: 'About', to: '/#about' },
  { label: 'Services', to: '/#services' },
  { label: 'Gallery', to: '/#gallery' },
  { label: 'Service Areas', to: '/#service-area' },
  { label: 'Financing', to: '/#financing' },
  { label: 'Blog', to: '/#blog' },
  { label: 'Contact', to: '/#cta-form' },
];

// Rule 62 + Rule 65: nav CTA buttons render --on-accent text on the accent
// gradient. inject-theme.mjs auto-picks --on-accent (white for blue/navy/red
// brands, dark navy for yellow/cream brands) so the letters stay readable
// across the full palette. Previously hardcoded #FFFFFF which made the CTA
// text invisible on yellow-accent brands (Remodeling MD: 1.00:1 contrast).
const navCtaTextStyle = {
  color: 'rgb(var(--on-accent))',
  textShadow: '0 1px 2px rgba(0, 0, 0, 0.18)',
};

export default function Navbar() {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [mobileServicesOpen, setMobileServicesOpen] = useState(false);
  const [servicesOpen, setServicesOpen] = useState(false);
  const dropdownRef = useRef(null);
  const location = useLocation();

  useEffect(() => {
    setMobileOpen(false);
    setServicesOpen(false);
    setMobileServicesOpen(false);
  }, [location.pathname]);

  useEffect(() => {
    const handler = (e) => {
      if (dropdownRef.current && !dropdownRef.current.contains(e.target)) {
        setServicesOpen(false);
      }
    };
    document.addEventListener('mousedown', handler);
    return () => document.removeEventListener('mousedown', handler);
  }, []);

  const scrollToForm = () => {
    const el = document.getElementById('quote') || document.getElementById('cta-form');
    if (el) el.scrollIntoView({ behavior: 'smooth' });
  };

  const isActive = (to) => {
    if (to === '/') return location.pathname === '/';
    return location.pathname.startsWith(to);
  };

  // Rule 63: nav surfaces honor brandDNA.nav_treatment. When the brand-dna
  // agent flags a contrast risk (logo contains white / light elements that
  // would vanish against the default light-theme flipped nav), nav_treatment
  // is set to "dark" and every nav surface adds theme-keep-dark so bg-navy
  // stays dark in light mode and child text-white stays white.
  const navDark = brandDNA.nav_treatment === 'dark';
  const themeKeep = navDark ? ' theme-keep-dark' : '';

  return (
    // Rule 54: nav element keeps a solid bg-navy in dark theme and bg-white/90
    // with backdrop-blur in light theme (handled by the light-theme override)
    // so the logo never reads against the hero photo behind it. Position
    // relative + z-index lift on the inner row keeps the logo above the hero.
    <nav className={`fixed top-0 left-0 right-0 z-50 shadow-lg bg-navy${themeKeep}`}>
      {/* Thin gold accent line at very top */}
      <div className="line-gold w-full" />

      <div className="max-w-7xl mx-auto px-4 flex items-center h-24 md:h-28 gap-4">
        {/* Logo. Rule 54: relative + z-index 20 so the wordmark sits ABOVE the
            hero section and the height cap (h-20 md:h-24) keeps the logo
            inside the nav bar even when the source SVG is tall.
            Rules 96 + 104: when nav_treatment === 'dark', swap to the
            white-knockout variant generated by build-from-template.py at
            /logo-white.webp. The nav surface is bg-navy in this case so the
            full-color logo would clash; white knockout reads cleanly. Rule 104
            (2026-06-02) permits the served white-knockout variant and supersedes
            Rule 96's (2026-05-28) preference for a brightness(0) invert(1) CSS
            filter on this dark-nav path. */}
        <Link to="/" className="flex-shrink-0 relative" style={{ zIndex: 20 }}>
          <img
            src={navDark ? '/logo-white.webp' : '/logo.webp'}
            alt={brandDNA.company.name}
            className="h-20 md:h-24 w-auto"
          />
        </Link>

        {/* Desktop nav */}
        <div className="hidden lg:flex items-center gap-5 ml-auto">
          {navLinks.map((link) =>
            link.dropdown === 'services' ? (
              <div key={link.label} className="relative" ref={dropdownRef}>
                <button
                  onClick={() => setServicesOpen(!servicesOpen)}
                  className={`font-body font-semibold text-sm flex items-center gap-0.5 whitespace-nowrap transition-colors pb-1 ${
                    isActive(link.to)
                      ? 'text-white border-b-2 border-gold'
                      : 'text-cool hover:text-white border-b-2 border-transparent'
                  }`}
                >
                  {link.label}
                  <svg className={`w-3 h-3 ml-0.5 text-steel transition-transform ${servicesOpen ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                {servicesOpen && (
                  <div className={`absolute top-full left-0 mt-2 w-56 shadow-2xl border border-steel/30 py-2 z-50 bg-navy-slate${themeKeep}`}>
                    <Link
                      to="/services"
                      className="block px-4 py-2 text-xs font-body font-bold text-gold uppercase tracking-wider hover:bg-navy transition-colors border-b border-steel/20 mb-1"
                    >
                      All Services →
                    </Link>
                    {serviceItems.map((s) => (
                      <Link
                        key={s.slug}
                        to={`/services/${s.slug}`}
                        className="block px-4 py-1.5 text-xs font-body font-semibold text-cool hover:text-white hover:bg-navy transition-colors"
                      >
                        {s.label}
                      </Link>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              <Link
                key={link.label}
                to={link.to}
                className={`font-body font-semibold text-sm whitespace-nowrap transition-colors pb-1 ${
                  isActive(link.to)
                    ? 'text-white border-b-2 border-gold'
                    : 'text-cool hover:text-white border-b-2 border-transparent'
                }`}
              >
                {link.label}
              </Link>
            )
          )}

          {/* Phone with available-now indicator. Rule 56 (refresh): the dot
              ALWAYS renders next to the phone number on every desktop
              breakpoint, not just xl. The label is hidden under xl so the
              dot fits without crowding the nav links. */}
          <a href={`tel:${brandDNA.contact.phoneTelLink}`} className="flex items-center gap-2 ml-1">
            <span className="hidden xl:inline-flex">
              <AvailableDot size="sm" label={true} />
            </span>
            <span className="inline-flex xl:hidden">
              <AvailableDot size="sm" label={false} />
            </span>
            <span className="font-body font-semibold text-sm text-cool whitespace-nowrap">{brandDNA.contact.phone}</span>
          </a>

          {/* Locked phrase: SOP allows only "Get My Free Estimate" as the
              primary CTA across the entire site. Sourced from
              brandDNA.copy.buttonText, which defaults to that exact string.
              Rule 62: white text + drop shadow so letters stay crisp on the
              metallic accent gradient. */}
          <button
            onClick={scrollToForm}
            className="btn-gold font-heading font-bold text-xs uppercase px-5 py-2.5 tracking-wider ml-1 whitespace-nowrap"
            style={navCtaTextStyle}
          >
            {brandDNA.copy.buttonText}
          </button>
        </div>

        {/* Mobile: CTA between logo and hamburger. Rule 56 (refresh): the
            dot is ALWAYS present in the mobile slot, with the label visible
            from the sm breakpoint up so the office hours signal carries
            even on 375px viewports. Rule 62 keeps the text white + shadow
            across breakpoints. */}
        <div className="lg:hidden ml-auto mr-2 flex items-center gap-2">
          <a
            href={`tel:${brandDNA.contact.phoneTelLink}`}
            className="hidden sm:inline-flex"
            aria-label="Call now"
          >
            <AvailableDot size="sm" label={true} />
          </a>
          <a
            href={`tel:${brandDNA.contact.phoneTelLink}`}
            className="sm:hidden inline-flex"
            aria-label="Call now"
          >
            <AvailableDot size="sm" label={false} />
          </a>
          <a
            href={`tel:${brandDNA.contact.phoneTelLink}`}
            className="flex items-center gap-1.5 font-heading font-bold text-xs uppercase px-3 py-1.5 tracking-wider"
            style={{
              background: 'linear-gradient(135deg, rgb(var(--accent-light)) 0%, rgb(var(--accent)) 40%, rgb(var(--accent-dark)) 65%, rgb(var(--accent-light)) 100%)',
              ...navCtaTextStyle,
            }}
          >
            <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
            </svg>
            Call Now
          </a>
        </div>

        {/* Mobile hamburger */}
        <button
          className="lg:hidden text-white"
          onClick={() => setMobileOpen(!mobileOpen)}
        >
          <svg className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d={mobileOpen ? 'M6 18L18 6M6 6l12 12' : 'M4 6h16M4 12h16M4 18h16'} />
          </svg>
        </button>
      </div>

      {/* Mobile menu */}
      {mobileOpen && (
        <div className={`lg:hidden border-t border-steel/20 px-4 py-3 flex flex-col gap-0.5 bg-navy${themeKeep}`}>
          {/* Rule 56 (refresh): when the hamburger expands, surface the
              available-now indicator inside the menu so the signal carries
              over to the expanded mobile nav. */}
          <div className="py-2 border-b border-steel/20">
            <AvailableDot size="sm" label={true} />
          </div>
          {navLinks.map((link) =>
            link.dropdown === 'services' ? (
              <div key={link.label}>
                <button
                  onClick={() => setMobileServicesOpen(!mobileServicesOpen)}
                  className="w-full text-left font-body font-semibold text-sm py-2.5 border-b border-steel/20 flex items-center justify-between text-cool hover:text-white"
                >
                  {link.label}
                  <svg className={`w-3 h-3 transition-transform ${mobileServicesOpen ? 'rotate-180' : ''}`} fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                  </svg>
                </button>
                {mobileServicesOpen && (
                  <div className="pl-3 py-1 flex flex-col gap-0.5">
                    {serviceItems.map((s) => (
                      <Link
                        key={s.slug}
                        to={`/services/${s.slug}`}
                        className="text-xs font-body font-semibold py-1.5 text-steel hover:text-white"
                      >
                        · {s.label}
                      </Link>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              <Link
                key={link.label}
                to={link.to}
                className="font-body font-semibold text-sm py-2.5 border-b border-steel/20 last:border-b-0 text-cool hover:text-white"
              >
                {link.label}
              </Link>
            )
          )}
          {/* Rule 62: collapsed nav CTA also uses white text + shadow */}
          <button
            onClick={() => { scrollToForm(); setMobileOpen(false); }}
            className="mt-2 btn-gold font-heading font-bold text-sm uppercase px-4 py-2.5 tracking-wider text-center w-full"
            style={navCtaTextStyle}
          >
            {brandDNA.copy.buttonText}
          </button>
        </div>
      )}
    </nav>
  );
}
